### ISSUE TITLE
App force close after selecting an Image

### ISSUE THREAD

**Issue by VeeraAndroid** [freddieptf/MediaCompressor#1]
i check your APK. Can choose video only but not compress the video. Choose image ANR issue in Samsung S5 device.

**Comment by freddieptf** [comment]
Hi, I'm currently working on the video compression part, it's not fully functional yet. For the ANR issue, [download the new apk](https://github.com/freddieptf/MediaCompressor/raw/master/apk/app-debug.apk) and see if happens again.

**Comment by VeeraAndroid** [comment]
Still have Choose image ANR issue in Samsung S5 device.

[ CHOOSE IMAGE -> PICK IMAGE FROM (GALLERY) -> ALBUM -> choose any one
image -> ANR ]


 *Veera*
 Android Developer
  +91-9941510691
<https://www.facebook.com/mygooi?fref=nf> <https://twitter.com/mygooi>
<http://www.pinterest.com/mygooi/> <http://instagram.com/iamgooination>
<https://www.youtube.com/user/gooination>

**Comment by freddieptf** [comment]
I replicated the issue and fixed it. Was a vector drawable issue in the list selector so it only affected devices running Kitkat and below. [apk] (https://github.com/freddieptf/MediaCompressor/raw/master/apk/app-debug.apk)
